# Generated by Django 4.2.6 on 2023-11-18 09:37

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import modelViewer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ThreeDModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='3dmodel_images/')),
                ('file', models.FileField(help_text='Please use only .blend files', upload_to='3dmodels/', validators=[modelViewer.models.validate_gltf_file])),
                ('rating_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('categories', models.ManyToManyField(to='modelViewer.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
    ]
