# Generated by Django 4.2.6 on 2023-11-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0002_alter_threedmodel_file_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threedmodel',
            name='rating_average',
        ),
        migrations.AddField(
            model_name='threedmodel',
            name='ratings',
            field=models.ManyToManyField(blank=True, related_name='model_ratings', to='modelViewer.rating'),
        ),
    ]
