# Generated by Django 4.2.6 on 2023-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='categories',
            field=models.ManyToManyField(to='modelViewer.category'),
        ),
    ]
