# Generated by Django 4.2.6 on 2023-12-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0004_remove_threedmodel_ratings_rating_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
