# Generated by Django 4.2.6 on 2023-11-16 10:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import modelViewer.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelViewer', '0004_threedmodel_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='file',
            field=models.FileField(help_text='Use only .blend files', upload_to='3dmodels/', validators=[modelViewer.models.validate_blend_file]),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
    ]
