# Generated by Django 4.2.6 on 2023-11-16 10:42

from django.db import migrations, models
import modelViewer.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0005_alter_threedmodel_description_alter_threedmodel_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threedmodel',
            name='file',
            field=models.FileField(help_text='Please use only .blend files', upload_to='3dmodels/', validators=[modelViewer.models.validate_blend_file]),
        ),
    ]
