# Generated by Django 4.2.6 on 2023-11-16 11:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modelViewer', '0006_alter_threedmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='3dmodel_images/'),
        ),
        migrations.AlterField(
            model_name='threedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=django.contrib.auth.models.User),
        ),
    ]
