# Generated by Django 4.2.6 on 2023-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0008_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload an image', null=True, upload_to='profile_pics/'),
        ),
    ]
