# Generated by Django 4.2.6 on 2023-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelViewer', '0009_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='threedmodel',
            name='textures',
            field=models.FileField(blank=True, help_text='Please upload your textures here', null=True, upload_to='3dtextures/'),
        ),
    ]
